use rusqlite::{ToSql, types::FromSql};

use crate::models::ip::TruncatedIp;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct UserId(i64);

impl FromSql for UserId {
    fn column_result(value: rusqlite::types::ValueRef<'_>) -> rusqlite::types::FromSqlResult<Self> {
        Ok(UserId(value.as_i64()?))
    }
}

impl ToSql for UserId {
    fn to_sql(&self) -> rusqlite::Result<rusqlite::types::ToSqlOutput<'_>> {
        Ok(self.0.into())
    }
}

/// Data for associating specific comments/stars to users. Contains a unique id from the db and a
/// hex string of 128 bits generated by the server and stored by the browser to identify users
#[derive(Debug)]
pub struct User {
    id: UserId,
    display_name: String,
    token: String,
    color: Color,
    banned: bool,
    associated_ip: TruncatedIp,
}
impl User {
    pub fn from_row(row: &rusqlite::Row<'_>) -> Result<Self, rusqlite::Error> {
        Ok(Self {
            id: row.get(0)?,
            display_name: row.get(1)?,
            token: row.get(2)?,
            color: row.get(3)?,
            banned: row.get(4)?,
            associated_ip: row.get(5)?,
        })
    }

    pub fn get_id(&self) -> UserId {
        self.id
    }
    pub fn get_token(&self) -> &str {
        &self.token
    }
    pub fn get_color(&self) -> Color {
        self.color
    }
    pub fn get_display_name(&self) -> &str {
        &self.display_name
    }
}

#[derive(Copy, Clone)]
pub struct Color(u32);

impl Color {
    pub const WHITE: Color = Color(u32::MAX);
}

impl std::fmt::Debug for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let bytes = self.0.to_be_bytes();
        f.write_fmt(format_args!(
            "Color: #{:x}{:x}{:x}",
            bytes[0], bytes[1], bytes[2]
        ))
    }
}

impl std::fmt::Display for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let bytes = self.0.to_ne_bytes();
        f.write_fmt(format_args!("#{:x}{:x}{:x}", bytes[0], bytes[1], bytes[2]))
    }
}

impl FromSql for Color {
    fn column_result(value: rusqlite::types::ValueRef<'_>) -> rusqlite::types::FromSqlResult<Self> {
        let color_int = value.as_i64()? as u32;
        Ok(Color(color_int))
    }
}
