use rusqlite::{ToSql, types::FromSql};

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct UserId(i64);

impl FromSql for UserId {
    fn column_result(value: rusqlite::types::ValueRef<'_>) -> rusqlite::types::FromSqlResult<Self> {
        Ok(UserId(value.as_i64()?))
    }
}

impl ToSql for UserId {
    fn to_sql(&self) -> rusqlite::Result<rusqlite::types::ToSqlOutput<'_>> {
        Ok(self.0.into())
    }
}

/// Data for associating specific comments/stars to users. Contains a unique id from the db and a
/// hex string of 128 bits generated by the server and stored by the browser to identify users
#[derive(Debug)]
pub struct User {
    id: UserId,
    token: String,
}
impl User {
    pub fn from_row(row: &rusqlite::Row<'_>) -> Result<Self, rusqlite::Error> {
        Ok(Self {
            id: row.get(0)?,
            token: row.get(1)?,
        })
    }

    pub fn get_id(&self) -> UserId {
        self.id
    }
    pub fn get_token(&self) -> &str {
        &self.token
    }
}
